DROP TABLE CHAMBA.Bonos
DROP TABLE CHAMBA.Cambio_Plan
DROP TABLE CHAMBA.Compra_Bonos
DROP TABLE CHAMBA.Consultas
DROP TABLE CHAMBA.Funcionalidad_X_Rol
DROP TABLE CHAMBA.Funcionalidades
DROP TABLE CHAMBA.Rol_X_Usuario
DROP TABLE CHAMBA.Roles
DROP TABLE CHAMBA.Tipo_Especialidad_X_Profesional
DROP TABLE CHAMBA.Turnos
DROP TABLE CHAMBA.Agenda
DROP TABLE CHAMBA.Cancelaciones
DROP TABLE CHAMBA.Pacientes
DROP TABLE CHAMBA.Profesionales
DROP TABLE CHAMBA.Planes
DROP TABLE CHAMBA.Usuarios
DROP TABLE CHAMBA.Tipo_Especialidad
DROP TABLE CHAMBA.Especialidades

DROP PROCEDURE CHAMBA.CargarAfiliados
DROP PROCEDURE CHAMBA.CargarTurnos
DROP PROCEDURE CHAMBA.ComprarBonos
DROP PROCEDURE CHAMBA.CargarBonosParaTurno
DROP PROCEDURE CHAMBA.EliminarAfiliado
DROP PROCEDURE CHAMBA.EspecialidadesCanceladas
DROP PROCEDURE CHAMBA.EsAfiliado
DROP PROCEDURE CHAMBA.HistorialCambiosPlan
DROP PROCEDURE CHAMBA.ModificarAfiliado
DROP PROCEDURE CHAMBA.ModificarPlan
DROP PROCEDURE CHAMBA.ObtenerNuevoIdBono
DROP PROCEDURE CHAMBA.ObtenerNuevoIdPaciente
DROP PROCEDURE CHAMBA.ObtenerPrecioDeBono
DROP PROCEDURE CHAMBA.ObtenerProximoIdFamiliar
DROP PROCEDURE CHAMBA.TieneConyuge
DROP PROCEDURE CHAMBA.VerificarLogin

DROP FUNCTION CHAMBA.RolesActivos


DROP SCHEMA CHAMBA